### ISSUE TITLE
dropdownBox function missing?

### ISSUE THREAD

**Issue by hack-r** [cran/shinydashboardPlus#1]
I just installed for the first time (so it shouldn't be out of date?) but I can't run the example because of

```
Error in dropdownBlock(id = "mydropdown", title = "Dropdown 1", icon = icon("sliders"),  : 
  could not find function "dropdownBlock"
```

Many thanks. I will continue to see if I can fix/update it on my side. I noticed there's no installation instructions in the package. I see them on the repo. Would be a nice to add sometime to the help pages.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file.
